---
abstract: ~
author:
  - 'Dave Lambley, based on work by Tomas (t0m) Doran.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Pod::Coverage: 0.19
  Pod::Coverage::TrustPod: 0
  Test::More: 0.88
  Test::NoTabs: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Spelling: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: AGPL_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing::AMQP::Proxy
name: Message-Passing-AMQP-Proxy
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::RabbitMQ: 1.05
  JSON: 0
  JSON::XS: 0
  Message::Passing: 0.009
  Message::Passing::AMQP: 0.003
  Moose: 0
  Task::Weaken: 0
  Try::Tiny: 0
  namespace::autoclean: 0
version: 0.002
